fix: SearchFilterForm mobile view
arifulbgt4/Marketplace pull request #88
Opened 2023-10-31 13:21 UTC by Mdjuealhossain

2023-10-31 15:27 UTC, arifulbgt4 requested changes

2023-10-31 15:27 UTC, arifulbgt4 commented on src/components/Logo/index.tsx
>          DREAM HOUSE
Svg icon should placed here

2023-10-31 15:27 UTC, arifulbgt4 commented on src/layouts/AppLayout/index.tsx
> +      <Grid item xs={12} height="calc(100% - 56.7px)">
Move to variable the header height

2023-10-31 15:30 UTC, Mdjuealhossain commented
![Screenshot_11](https://github.com/arifulbgt4/Marketplace/assets/123495777/6f2eef2f-72fe-42f2-aa09-feddf8e0c391)
![Screenshot_10](https://github.com/arifulbgt4/Marketplace/assets/123495777/e5048887-7616-4a74-b49c-cecebea2db64)

2023-11-01 06:15 UTC, arifulbgt4 requested changes

2023-11-01 06:15 UTC, arifulbgt4 commented on src/layouts/AppLayout/index.tsx
> +  const headerHeight = 64;
remove header height

2023-11-01 06:20 UTC, arifulbgt4 requested changes

2023-11-01 06:20 UTC, arifulbgt4 commented on src/widgets/ListSearchFilters/Types.ts
> +  onClose?: () => void;
onCloseMobileDrawer

2023-11-01 06:20 UTC, arifulbgt4 commented on src/widgets/SearchListingGroup/index.tsx
> +  const handleGridList = (event: boolean) => {
toggleGridList

2023-11-01 06:20 UTC, arifulbgt4 commented on src/widgets/SearchListingGroup/index.tsx
>      setIsGrid(event);
setIsG(!isGrid)

2023-11-04 15:56 UTC, arifulbgt4 approved these changes

2023-11-04 15:57 UTC, merged